version: '3'

tasks:
  dev:
    desc: 'Run the arbiter in development mode'
    env:
      CANISTER_ROOT_CERT:
        sh: realpath ./certs/cnstr_ca.crt
      CANISTER_ROOT_KEY:
        sh: realpath ./certs/cnstr_ca.key
    cmds:
      - go run ./cmd/arbiter
