version: '3'

tasks:
  dev:
    desc: 'Run the arbiter in development mode'
    env:
      ROOT_CA_CERT:
        sh: realpath ./certs/cnstr_ca.crt
      ROOT_CA_KEY:
        sh: realpath ./certs/cnstr_ca.key
    cmds:
      - go run ./cmd/arbiter
