version: '3'

tasks:
  dev:
    desc: 'Run the arbiter in development mode'
    env:
      ROOT_CERT:
        sh: realpath ./certs/root.crt
      ROOT_KEY:
        sh: realpath ./certs/root.key
      TYPESENSE_PUBLIC_API_KEY: 'cnstr'
      TYPESENSE_PRIVATE_API_KEY: 'typesense'
      TYPESENSE_HOST: 'http://localhost:7700'
    cmds:
      - go run ./cmd/arbiter
